version: '2'
services:
  es:
   image: vulhub/elasticsearch:1.1.1
   ports:
    - "3120:9200"
    - "3121:9300"
   hostname: es
  wait_for_service:
    image: alpine:latest
    command: >
        sh -c 'apk --no-cache add curl && sleep 10 && curl http://es:9200/website/blog/ -X POST -H "Content-Type: application/json" -d "{\"name\": \"phithon\"}"'
    depends_on:
      - es